apiVersion: v1
kind: Service
metadata:
  name: my-clusterip
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - name: http
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - nodePort: 31001
      port: 8080
      targetPort: 80
